### ISSUE TITLE
Comments "you" (the user) made are in a weird blue color 

### ISSUE THREAD

**Issue by ghost** [vednoc/dark-github#6]
Comments you make is in a weird blue color (don't know if this is intentional or not but it looks odd in a way)

## Screenshots

![image](https://user-images.githubusercontent.com/66189242/120489255-0671ad00-c3a7-11eb-8fdd-5f0ae6b1198a.png)
![image](https://user-images.githubusercontent.com/66189242/120490260-c8c15400-c3a7-11eb-8f23-331a8ea3c58f.png)

## More info

I also have some extensions that changes how github looks / added features but it still happens when they're disabled :c

**Comment by vednoc** [comment]
Thank you for reporting this issue. It will look a lot better across all color-schemes in the next release:

![image](https://user-images.githubusercontent.com/18245694/120557380-19fc3280-c3fe-11eb-8ac9-15db96bc2b24.png)
