### ISSUE TITLE
Something needs a fix

### ISSUE THREAD

**Issue by MyCodeIsntWorking** [vednoc/dark-github#8]
It would be awesome if you can fix that.
![Unbenannt](https://user-images.githubusercontent.com/48364251/133138059-10ef8d2f-f5d5-4da3-af5f-ec05ec4b9b73.png)
![Unbenannt-2](https://user-images.githubusercontent.com/48364251/133138078-965ed87e-43be-49c8-b3e3-a51a536f58cd.png)

**Comment by JotaPe** [comment]
![image](https://user-images.githubusercontent.com/17516509/133139680-158f9950-5662-4ddd-9afa-b2a5e1f7de84.png)

Using Dark-Switcher too.

**Comment by vednoc** [comment]
GitHub added new color variables. I fixed the ones that I could find in `v1.2.1`; let me know if you happen to find more unstyled/broken ones.

**Comment by JotaPe** [comment]
> GitHub added new color variables. I fixed the ones that I could find in `v1.2.1`; let me know if you happen to find more unstyled/broken ones.

Working fine right now thanks vednoc, continue with the great work!

**Comment by MyCodeIsntWorking** [comment]
All perfect now. Thank you and keep going with your fine work ♥
